import React from 'react'
import { useRouter } from "next/router";
import { Typography } from '@mui/material';
import styles from "../../styles/category.module.css"
import Head from 'next/head';
import ProductCard from '../../components/productCard';
import { data } from '../../data/sample';

  

export default function Category() {


    const router = useRouter()
    const title = router.query.category

    return (
        <div className={styles.container}>
            <Head>
                <title>JOMAC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.heading}>
                    <Typography variant="h3" color="primary">{title}</Typography>
                </div>
                <div className={styles.productGrid}>
                {data.map((product)=>{
                    return(
                        <ProductCard 
                        product={product}
                       />
                    )
                })}
                    
                 </div>

            </main>
        </div>
    )
}
