import React from 'react'
import { useRouter } from "next/router";
import { Box, Typography } from '@mui/material';
import { Container, Grid } from '@mui/material'
import styles from "../../styles/category.module.css"
import Head from 'next/head';
import ProductCard from '../../components/productCard';
import { data } from '../../data/sample';


export default function Category() {


    const router = useRouter()
    const title = router.query.category

    return (
        <div className={styles.container}>
            <Head>
                <title>JOMAC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Box component="main"
                sx={{
                    flexGrow: 1,
                    py: 8,
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center'
                }}

            >
                <div className={styles.heading}>
                    <Typography variant="h3" color="primary">{title}</Typography>
                </div>
                <Container maxWidth={false} className={styles.mainBox}>
                    <Grid
                        container
                        spacing={6}
                    >
                        {data.map((product) => {
                            return (
                                <Grid
                                    item
                                    lg={3}
                                    sm={4}
                                    xl={3}
                                    xs={6}
                                >
                                    <ProductCard
                                        product={product}
                                    />

                                </Grid>

                            )
                        })}
                    </Grid>
                </Container>

            </Box>
        </div>
    )
}
