import Head from 'next/head'

import styles from '../styles/categories.module.css'
import { Box, Typography, Grid, Card, CardContent, CardMedia, Button } from '@mui/material'
import { categories } from '../menuItems/categories'

export default function category() {
    return (
        <div className={styles.container}>
            <Head>
                <title>JOMAC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Box
                sx={{
                    flexGrow: 1,
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center'
                }}

            >

                <div
                    className={styles.heroSection}>
                    <div
                        className={styles.heroText}>
                        <Typography variant="h1">
                            Categories
                        </Typography>
                    </div>
                </div>

                <Grid
                    container
                    spacing={6}
                    sx={{px:2}}
                >
                    {
                        categories.map((cat, index) => (
                            <Grid
                                item
                                xs={12}
                                sm={6}
                                md={6}
                                lg={3}
                                xl={3}
                                key={index}
                            >
                                <Card elevation={12}>
                                    <CardMedia
                                        image={cat.image}
                                        alt={cat.title}
                                        sx={{ width: '100%', height: '15vh' }}
                                    />
                                    <CardContent>
                                        <Typography variant="h3">{cat.title}</Typography>
                                        <Typography variant="body1" sx={{ fontWeight: 400 }}>{cat.body}</Typography>
                                    </CardContent>
                                    <Box sx={{display:'flex', justifyContent:'flex-end',px:2,py:2}}>
                                        <Button href={cat.url} color="primary" variant='contained'>View</Button>
                                    </Box>
                                </Card>

                            </Grid>
                        ))
                    }

                </Grid>

            </Box>
        </div>
    )
}
