import Head from 'next/head'

import styles from '../styles/contacts.module.css'

import { Box, Card, Container, Grid, Typography } from '@mui/material'
import { AiFillPhone, AiOutlineMail } from "react-icons/ai"
import ContactCard from '../components/contactCard'

export default function Contact(props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>JOMAC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Box component="main"
                sx={{
                    flexGrow: 1,
                    py: 8,
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center'
                }}

            >

                <div className={styles.heroSection}>
                    <Typography variant='h1'>Get in touch</Typography>
                    <Typography variant="body1">Contact us or visit our shop</Typography>

                </div>

                <Container maxWidth={false} className={styles.mainBox}>
                    <Grid
                        container
                        spacing={6}
                    >
                        <Grid
                            item
                            lg={6}
                            sm={6}
                            xl={6}
                            xs={12}
                        >
                            <ContactCard icon={<AiFillPhone size={40} />} title="+265884568525" />
                        </Grid>
                        <Grid
                            item
                            lg={6}
                            sm={6}
                            xl={6}
                            xs={12}
                        >
                            <ContactCard icon={<AiOutlineMail size={40} />} title="malunje69@gmail.com" />
                        </Grid>

                    </Grid>
                </Container>
    
            </Box>
        </div>
    )
}
