import Head from 'next/head'
import Image from 'next/image'
import CategoryCard from '../components/categoryCard'
import styles from '../styles/Home.module.css'
import hero from "../public/hero.png"
import { Box, Container, Grid, Typography } from '@mui/material'
import { categories } from '../menuItems/categories'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>JOMAC</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <Box component="main"
        sx={{
          flexGrow: 1,
          py: 8,
          display: 'flex',
          flexDirection: 'column',
          justifyContent: 'center',
          alignItems: 'center'
        }}

      >

        <div className={styles.heroSection}>
          <div className={styles.heroText}>
            <Typography variant="h1">
              Your Construction Needs
            </Typography>
            <Typography variant="h1">
              Our Priority
            </Typography>

          </div>
        </div>
        <Typography variant="h3"  className={styles.categoryHeading}>Browse by Category</Typography>
        <Container maxWidth={false} className={styles.mainBox}>
          <Grid
            container
            spacing={4}
          >
            {
              categories.map((cat, index) => (
                <Grid
                  item
                  lg={3}
                  sm={6}
                  xl={3}
                  xs={6}
                  key={index}
                >
                  <CategoryCard image={cat.image} title={cat.title} url={cat.url} key={index} />
                </Grid>
              ))
            }
          </Grid>
        </Container>
      </Box>
    </div>
  )
}
