import React from 'react'
import { Box, Paper, Typography } from '@mui/material';
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import { Container } from '@mui/material'
import styles from "../styles/order.module.css"
import Head from 'next/head';
import { useState, useEffect } from 'react';
import axios from 'axios';

import CartItem from '../components/cartItem';
import { getCart } from '../cart/actions';
import OrderList from '../components/orderList';

export default function Order() {

    

    return (
        <div className={styles.container}>
            <Head>
                <title>JOMAC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <Box
                sx={{
                    flexGrow: 1,
                    display: 'flex',
                    flexDirection: 'column',
                    justifyContent: 'center',
                    alignItems: 'center'
                }}

            >
                <div className={styles.heading}>
                    <Typography variant="h1" >Your Order</Typography>
                </div>
                <div className={styles.tableContainer}>
                    <TableContainer component={Paper}>
                        <Table aria-label="simple table">
                            <TableHead>
                                <TableRow>
                                    <TableCell>Name</TableCell>
                                    <TableCell align="right">Quantity</TableCell>
                                    <TableCell align="right">Remove</TableCell>
                                </TableRow>
                            </TableHead>
                            <TableBody>
                                <OrderList/>
                            </TableBody>
                        </Table>

                    </TableContainer>
                </div>


            </Box>
        </div>
    )
}
