import { Typography } from '@mui/material';
import Head from 'next/head';
import React from 'react';
import styles from "../styles/products.module.css"

export default function products() {
    return (
        <div className={styles.container}>
            <Head>
                <title>JOMAC</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <div className={styles.hero}>
                    <Typography variant="h3" color="primary">All Products</Typography>
                </div>

                <div className={styles.productGrid}>
                    
                </div>


            </main>
        </div>

    );
}
